#!/bin/bash

#Java installation
apt update
apt install openjdk-11-jre -y
java -version

#Jenkins installation
curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
  /usr/share/keyrings/jenkins-keyring.asc > /dev/null
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null
apt-get update
apt-get install jenkins -y

#Enable and check Jenkins service
systemctl enable jenkins
systemctl start jenkins

#Run Jenkins on different port
#type this command "systemctl edit jenkins"
#Add this strings
#[Service]
#Environment="JENKINS_PORT=XXXX"

#Docker installation
apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release  -y
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update
apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y

#Create docker group, and add current user to it
groupadd docker
usermod -aG docker $USER
# Don't forget about log out and lo in, and then use this command "newgrp docker"

#Add Jenkins user to Docker group
usermod -a -G docker jenkins
systemctl restart jenkins
#Firewall setup
#ufw allow 8080
#ufw enable
#ufw status

#Terraform installation
apt install curl -y
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
apt update
apt install terraform -y

#Ansible installation
apt update
apt install software-properties-common -y
add-apt-repository --yes --update ppa:ansible/ansible
apt install ansible -y
sleep 10
clear
echo "Jenkins admin's password is:"
#Read Jenkins admin password
cat /var/lib/jenkins/secrets/initialAdminPassword
